### ISSUE TITLE
Build runs but client cant access files

### ISSUE THREAD

**Issue by Aror** [alexnm/react-ssr#1]
I ran your example via npm run dev but I am unable to access the built files when navigating to localhost.  I get the "This site can’t be reached" error.

**Comment by alexnm** [comment]
sorry I missed this notification for some reason.

are you going to `http://localhost:2048`? I tested the demo again and it works well. Give me more details maybe to try to figure out the problem

**Comment by foxmicha** [comment]
I can confirm this also doesn't work for me. It appears that the `server.js` is never getting ran at all. A console log placed within that file does not executed.

Is there some global installs we are perhaps missing?

EDIT: I was able to get the server started by running `node index.js` instead of the webpack / nodemon commands found in the `npm run dev` script.

EDIT EDIT: Following the second [StackOverflow answer](https://stackoverflow.com/questions/35545093/webpack-watch-and-launching-nodemon) I was able to separate out the watch operations and run them concurrently. It seems like on Windows they are both blocking operations. The `webpack --watch` never returns so the script never executes `nodemon index.js`

My package.json now looks like this:
```JSON
"dev": "npm-run-all --parallel watch:server watch:client",
"watch:client": "webpack --watch --progress",
"watch:server": "nodemon index.js",
```

**Comment by alexnm** [comment]
A true, on windows it's a bit different. Have you tried running them with `&&` instead of `&`?

I pushed two separate tasks for running the client and the server: `npm run server` and `npm run client`

Please do a PR if you want with the npm-run-all package.

**Comment by foxmicha** [comment]
Changing the ampersand did not produce any changes.

I've created [a PR](https://github.com/alexnm/react-ssr/pull/4) for the changes that got it working on my machine. You might consider re-creating the package-lock.json. My local node version can only create npm-shrinkwrap.json files.
