### ISSUE TITLE
How to add styles?

### ISSUE THREAD

**Issue by VadimN92** [alexnm/react-ssr#2]
I tried to add some styles for component and I got errors like this: 

> react-ssr/src/components/Home.css: Unexpected token

How can I add styles for this project?

**Comment by alexnm** [comment]
Sorry I didn't get this notification for some reason ...

In order to import styles in the JS bundle, you need a css-loader in your webpack configuration. This repo does not currently have that as it was not the point of the project. The standard way is to use the `ExtractTextPlugin` package as described here - https://github.com/webpack-contrib/extract-text-webpack-plugin

In order to use simple css without mixing it with js, you can simply add an external sheet in your template that you generate on the server.
