### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jeremytenjo** [alexnm/react-ssr#27]
Hi @alexnm , 

Very useful example, How did you get the ` const reactDom = renderToString( jsx );` in `server.js` to not give you a `window is not defined` error?

Cheers

**Comment by alexnm** [comment]
Hey. You shouldn't have a reference to window in your render functions in the React components. that's why you are getting it most likely. window is safe to use on componentDidMount since that executes only on the client.

The other option is to wrap its access in a check (if typeof window !== 'undefined')

**Comment by jeremytenjo** [comment]
@alexnm I got it working, thank you for the explanation.

Cheers
